### ISSUE TITLE
작성 - 콜라보 요청 - 알람 - 콜라보 승인 : 페이지 및 유저플로우 구현

### ISSUE THREAD

**Issue by mugyeol** [ProjectBlueHair/FinalProject_FE#15]
## Description
설명을 작성해주세요.

## Task
- [x] a. 전체 재생 바 (react-h5-audio-player) 커스터마이징
- [x] b. 오디오 플레이 바 (waveSurfer) 커스터마이징
- [x] b-1. 로딩 UI 추가
- [x] c. 전체 재생 바 & 오디오 플레이 바 & 볼륨 컨트롤 박스 연동
- [x] d. 오디오 파일 추가 (drag and drop)
- [x] d-1. 재생바 토글 삭제
- [x] d-2. 오디오 파일 삭제
- [x] d-3. 오디오 파일 형식 제한 
- [x] d-4. 오디오 클릭 업로드 추가
- [x] e. post request전송 (다중 오디오 파일, 이미지(s3), input form)
- [ ] f. music part 선택 모달
- [x] f-1. music part 선택 유효성 검사
- [x] f-2. music part 선택 alert
- [x] g. 작성 / 콜라보리퀘, 승인 UI
- [x] h. 작성 / 콜라보리퀘, 승인 api 연결
- [x] j. alarm 모달 UI 작업
- [x] j-1. 알람-콜라보리퀘 승인 연결
- [x] k. 재생 바 모듈화 (상세 페이지에 주입)
- [x] l. 커스텀 alert 모달 

## trouble shooting 
- [x] a. file을 blob 형식으로 state에 저장할 수 없음 (경고)
-> 옵션 1. file url을 state로 관리하고 전송 전에 fetch로 파일을 가져와서 업로드. 

- [x] b. 멀티파트 폼 데이터 (파일 & json)이 제대로 전송되지 않음 (415 error)
- 헤더 config는 multipart & boundary ~ 가 제대로 설정된 상태 
- 옵션 1. 스프링 쪽에서 application / json 형식을 요구하는 상태인가? -> x 
- 옵션 2. json 객체를 stringfy만 해주는 것이 아니라 type을 application/json으로 지정하고 stringfy한 제이슨을 블롭 형식으로 만들어주어야함 -> 해결

## Etc
기타사항
- [x] 대략적인 에러 핸들링 
- [x] 작성 / 콜라보 이동 간 redux 상태 초기화
