### ISSUE TITLE
피드백 수정

### ISSUE THREAD

**Issue by kdh8615** [ProjectBlueHair/FinalProject_FE#156]
## Description
피드백 수정

## Task
- [x] 설정페이지 useState -> useReudcer 변경
- [x] 마이페이지 내정보 -> about me 수정
- [x] 마이페이지 공유와 소셜 홍보링크 비슷해보이는 부분 수정
- [x] 마이페이지 / 상세페이지 팔로우시 색상이 있으면 좋겠다는 부분 반영
- [x] 댓글 부분 크기 수정 필요
- [x] 공동 작업자 보기 짤리는 부분 수정 필요 
## Trouble shooting
- [x] trouble 1 

## Etc
기타사항
