### ISSUE TITLE
알람, 자신의 음원 관리 페이지

### ISSUE THREAD

**Issue by mugyeol** [ProjectBlueHair/FinalProject_FE#25]
## Description
전부 구현하기 어렵겠지만 토요일(230121) 발표 전까지 최대한 해볼 것

## Task
- [x]  알람 UI 구현 
- [ ]  알람 API 연결
- [ ] 자신의 음원 관리 페이지 UI 구현
- [ ] 자신의 음원 관리 페이지 API 연결

## Etc
기타사항
