### ISSUE TITLE
메인페이지 작업

### ISSUE THREAD

**Issue by mugyeol** [ProjectBlueHair/FinalProject_FE#3]
## Todo
- [x] MSW 로 서비스 워커 만들어서 무한 스크롤 테스트 해보기 
- [x] 뮤직 플레이어 로직 구현하기 
- [x] 메인 태그 리스트 추가하기 
- [ ] 메인 검색 모달 
- [x] API 연결 
- [x] 뮤직 플레이어와 재생중인 메인 포스트 연결
- [x] 타입스크립트 적용

### 1. [audioPlayer - skip next / previous event] 
- 같은 src로 바뀔 경우에 재시작 되지 않고 그대로 재생 이어감
