### ISSUE TITLE
리팩토링 [리액트 쿼리, styled components theme, 에러 핸들링, 배포자동화]

### ISSUE THREAD

**Issue by mugyeol** [ProjectBlueHair/FinalProject_FE#45]
## Description
- 리액트 쿼리 공부 및 적용해보기 
- styled component theme 적용해보기 
- 에러 핸들링 고도화 
- 배포 자동화 (AWS S3 + CloudFront)

## Before
리덕스 툴킷에서 thunk middleware로 비동기 api 통신 로직을 처리하고 있는데 코드가 필요 이상으로 복잡함. 

## After
react-query
직관적이고 간략한 비동기 api 통신 코드
서버사이드 데이터 핸들링을 위한 react-query의 다양한 도구 활용

styled components 
현재 글로벌 스타일 컴포넌트에 정의되어 있는 색상들(--ec~) var변수로 가져다 쓰는게 너무 비효율적이고 통일되어 있지 않음 
1. 변수로 편하게 가져다 쓸 수 있게 만들고 2. theme 적용해볼것 

에러 핸들링 
인터셉터에서 처리하도록 로직이 구현된 상태긴 한데 좀 더 나은 방법이 있는지 생각해 볼 것. 
if문 -> switch 문으로 바꿀것

## Task
- [ ] 공식문서 참고해서 메인페이지 react-query 적용
- [ ] react-query에서 제공하는 도구 하나 이상 사용해보기 (캐싱, out of data 처리 등)
- [x] 색상 변수화 시키기 
- [x] theme 적용 
- [x] 에러 핸들링 부분 swith문으로 변경
- [x] 배포 자동화
