### ISSUE TITLE
리팩토링

### ISSUE THREAD

**Issue by mugyeol** [ProjectBlueHair/FinalProject_FE#66]
## Description
설명을 입력해주세요.

## Before
변경전의 상황과 변경하려는 이유를 작성해주세요.

## After
변경후의 예상하는 구조를 작성해주세요.

## Todo
- [ ]  데이터 업데이트 잘 안되는 부분 수정 (로그인, 로그아웃, 알람)
- [ ]  콜라보 실패 시 게시글 삭제
- [ ]  테스트용 데이터, 파일들 정리

## ETC
