### ISSUE TITLE
소셜 로그인 및 마이페이지 작업

### ISSUE THREAD

**Issue by kdh8615** [ProjectBlueHair/FinalProject_FE#78]
## Description
소셜로그인(카카오), 마이페이지

## Task
- [ ] 소셜 로그인
- [ ] 마이페이지
- [ ] 회원가입 로직 수정
- [ ] alert모달 수정
- [ ] 페이지 상단 logo 및 제목 변경
- [ ] 카카오 공유기능 및 커스텀 작업

## Trouble shooting
- [ ] trouble 1 

## Etc
기타사항
